version: "3.8"
services:
  app:
    build: .
    container_name: order-system-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/order_system_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app_pass
      SPRING_DATA_REDIS_HOST: redis   # 新增：Redis 主机名
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis                         # 启动顺序：先 Redis 再 App
#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: pass
#      MYSQL_DATABASE: order_system_db
#      MYSQL_USER: app
#      MYSQL_PASSWORD: app_pass
#    ports: ["3306:3306"]
#    command: ["--default-authentication-plugin=mysql_native_password"]
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
#  app:
#    build: .
#    environment:
#      DB_USER: app
#      DB_PASS: app_pass
#    ports: ["8080:8080"]
#    depends_on: [mysql, redis]




