spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_system_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none        # 不自动建表，保留你已有的表结构
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: localhost   # 关键：用 localhost，因为是本机访问容器
      port: 6379

  rabbitmq:
    host: localhost         # 如果用 docker: -p 5672:5672
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 以下先保留注释，下一步增强时再开
    # publisher-confirm-type: correlated
    # publisher-returns: true

server:
  port: 8080

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: health,info   # 或 "*"（开发期）
  endpoint:
    health:
      probes:
        enabled: true          # 暴露 /actuator/health/liveness|readiness
      show-details: never      # 开发期可设 "when_authorized"